/* generated by gen_vectors.py -- do not edit */
#ifndef ROM_LINK_H
#define ROM_LINK_H
#include <stdint.h>

#define LADDER_N 13
static const int16_t LADDER_MODE[13] = {
    2, 1, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 0
};

static const int16_t LADDER_MOD[13] = {
    0, 0, 0, 1, 0, 0, 1, 1,
    1, 1, 2, 2, 2
};

static const int16_t LADDER_SPD[13] = {
    0, 0, 1, 0, 0, 1, 0, 1,
    2, 3, 1, 2, 3
};

static const double LADDER_SENS[LADDER_N] = { -17.9, -11.7, -11.8, -11.3, -7.6, -7.3, -7.0, -5.3, -3.8, -2.2, 0.7, 2.6, 4.7 };
static const double LADDER_RATE[LADDER_N] = { 7.8, 30.8, 46.2, 61.5, 117.6, 176.5, 235.3, 352.9, 470.6, 529.4, 705.9, 941.2, 1058.8 };
static const int32_t LC_PACKED[6] = {
    903757, 122, 786423, 422521, 275080, 610683
};

#define LC0_SEQ 3
#define LC0_ACK 1
#define LC0_RUNG 12
#define LC0_SNR -4.0
#define LC0_FREQ -48.0
#define LC0_FLAGS 5
#define LC1_SEQ 0
#define LC1_ACK 0
#define LC1_RUNG 0
#define LC1_SNR -99.0
#define LC1_FREQ 0.0
#define LC1_FLAGS 2
#define LC2_SEQ 2
#define LC2_ACK 3
#define LC2_RUNG 15
#define LC2_SNR 6.0
#define LC2_FREQ 120.0
#define LC2_FLAGS 7
#define LC3_SEQ 1
#define LC3_ACK 2
#define LC3_RUNG 7
#define LC3_SNR -20.0
#define LC3_FREQ 0.0
#define LC3_FLAGS 1
#define LC4_SEQ 1
#define LC4_ACK 0
#define LC4_RUNG 3
#define LC4_SNR -20.0
#define LC4_FREQ 16.0
#define LC4_FLAGS 0
#define LC5_SEQ 2
#define LC5_ACK 1
#define LC5_RUNG 5
#define LC5_SNR -22.0
#define LC5_FREQ 0.0
#define LC5_FLAGS 3
#define CTL_OPS_N 49
static const int16_t CTL_OP[49] = {
    1, 2, 0, 1, 6, 0, 0, 0,
    1, 2, 7, 6, 0, 0, 0, 1,
    2, 0, 0, 0, 1, 2, 3, 3,
    2, 3, 3, 2, 4, 2, 5, 5,
    5, 5, 2, 5, 2, 1, 1, 6,
    2, 1, 1, 1, 1, 0, 2, 0,
    2
};

static const double CTL_A[CTL_OPS_N] = { 0.0, 0.0, -16.0, 0.0, 0.0, -8.0, -7.5, -7.8, 0.0, 0.0, 0.0, 0.0, -2.0, -1.5, -1.8, 0.0, 0.0, -12.0, -12.5, -12.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 6.0, 6.0, 6.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -4.0, 0.0, -4.0, 0.0 };
static const int16_t CTL_B[49] = {
    0, 0, 0, 0, 0, 3, 4, 5,
    0, 0, 0, 0, 7, 8, 8, 0,
    0, 2, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 11, 0, 11,
    0
};

static const double CTL_C[CTL_OPS_N] = { 0.0, 0.0, -24.0, 0.0, 0.0, -6.0, -6.0, -5.8, 0.0, 0.0, 0.0, 0.0, -1.0, -0.5, -0.4, 0.0, 0.0, -13.0, -13.5, -13.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -99.0, 0.0, -20.0, 0.0 };
static const double CTL_T[CTL_OPS_N] = { 0.0, 0.0, 1.0, 1.5, 1.5, 10.0, 20.0, 30.0, 31.0, 31.0, 31.0, 31.0, 40.0, 50.0, 55.0, 56.0, 56.0, 60.0, 62.0, 64.0, 65.0, 65.0, 66.0, 70.0, 71.0, 74.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 120.0, 200.0, 200.0, 300.0, 400.0, 400.0, 400.0, 445.0, 310.0, 311.0, 320.0, 321.0 };
static const int32_t CTL_WANT[49] = {
    0, 0, 0, 0, -16000, 0, 0, 0,
    3, 5, 4, -8000, 0, 0, 0, 3,
    8, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, -99000,
    0, 0, 0, 0, 0, 0, 11, 0,
    0
};

#endif /* ROM_LINK_H */