"""Generate ROM tables and golden test vectors for the C port.

Emits:
  src/rom_tables.h   -- Q15 twiddle ROMs (128/256/512), NCO sine/cosine ROM,
                        Hilbert taps, CORDIC atan table + gain (all dumped
                        from the Python model so np.round conventions can
                        never diverge from a C reimplementation)
  tests/test_vectors.h -- golden inputs/outputs for the primitive modules,
                        embedded as C arrays (no file I/O, no endianness)

Run:  ../venv/bin/python gen_vectors.py
"""

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ofdm_phy.fixed.fft import _twiddles, fft_fixed, ifft_fixed, fft_bfp
from ofdm_phy.fixed.dsp import (HilbertFIR, NCO, cordic_atan2,
                                _CORDIC_ATAN, _CORDIC_GAIN_Q15)
from ofdm_phy.crc import crc8_lte, crc16_ccitt
from ofdm_phy.scrambler import scramble, descramble
from ofdm_phy.interleaver import interleave, deinterleave
from ofdm_phy.coding import CCLTEBPSK_13, CCLTEBPSK_12, CCLTEBPSK_23, CCLTEBPSK_34
from ofdm_phy.fixed.viterbi import viterbi_decode_int

from ofdm_phy.modes import LinkMode
from ofdm_phy.packets import Data, Header, PacketType, ModType, CCSpeed
from ofdm_phy.fixed import FixedTransmitter, FixedReceiver

RATES = [("R13", CCLTEBPSK_13), ("R12", CCLTEBPSK_12),
         ("R23", CCLTEBPSK_23), ("R34", CCLTEBPSK_34)]

FNV_OFFSET = 14695981039346656037
FNV_PRIME = 1099511628211
U64 = (1 << 64) - 1


def fnv64_i16(samples):
    h = FNV_OFFSET
    for s in np.asarray(samples, dtype=np.int64):
        h = ((h ^ (int(s) & 0xFFFF)) * FNV_PRIME) & U64
    return h


def fnv64_i64(values):
    h = FNV_OFFSET
    for v in np.asarray(values, dtype=np.int64):
        h = ((h ^ (int(v) & U64)) * FNV_PRIME) & U64
    return h


def gen_mode_roms():
    """Per-mode constants + preamble/pilot/LPF ROMs -> src/rom_modes.h."""
    out = ["/* generated by gen_vectors.py -- do not edit */",
           "#ifndef ROM_MODES_H", "#define ROM_MODES_H",
           "#include <stdint.h>", ""]
    ref = None
    for mode in LinkMode:
        tx = FixedTransmitter(mode)
        m = tx._m
        idx = (tuple(m.channel_indices), tuple(m._data_local_indices),
               tuple(m._pilot_local_indices))
        if ref is None:
            ref = idx
            out.append(carr("CHANNEL_IDX", m.channel_indices, "int16_t"))
            out.append(carr("DATA_LOCAL_IDX", m._data_local_indices, "int16_t"))
            out.append(carr("PILOT_LOCAL_IDX", m._pilot_local_indices, "int16_t"))
            out.append(carr("PILOT_RE", tx.pilot_rom[0], "int16_t"))
            out.append(carr("PILOT_IM", tx.pilot_rom[1], "int16_t"))
            out.append(carr("TX_LPF_TAPS", tx.lpf_q15, "int16_t"))
            out.append(f"#define N_CHANNEL {len(m.channel_indices)}")
            out.append(f"#define N_DATA_CARRIERS {len(m._data_local_indices)}")
            out.append(f"#define N_PILOTS {len(m._pilot_local_indices)}")
            out.append(f"#define CP_LEN {m.cyclic_prefix}")
            out.append(f"#define FFT_BINS {m.fft_bins}\n")
        else:
            assert idx == ref, "carrier layout differs between modes"
        out.append(f"#define SYM_TILE_{mode.name} {m.sym_tile}")
        out.append(f"#define PREAMBLE_LEN_{mode.name} {len(tx.preamble_rom)}")
        # the preamble is perfectly periodic piecewise -- store only the
        # unique blocks (32+64+128 samples vs up to 69664): tone field A
        # (2T tiles of a 32-sample block), tone field B (T tiles of a
        # 64-sample block), ZC symbol (CP = tail of one 128-sample tile,
        # then sym_tile tiles). tx.c re-expands with modulo indexing.
        pre = [int(v) for v in tx.preamble_rom]
        n_tail = m.cyclic_prefix + m.sym_tile * m.fft_bins
        T = (len(pre) - n_tail) // (3 * m.fft_bins)
        assert 3 * T * m.fft_bins + n_tail == len(pre)
        tone_a = pre[:32]
        tone_b = pre[2 * T * m.fft_bins:2 * T * m.fft_bins + 64]
        zc = pre[3 * T * m.fft_bins + m.cyclic_prefix:
                 3 * T * m.fft_bins + m.cyclic_prefix + m.fft_bins]
        rebuilt = ([tone_a[i % 32] for i in range(2 * T * m.fft_bins)]
                   + [tone_b[i % 64] for i in range(T * m.fft_bins)]
                   + zc[m.fft_bins - m.cyclic_prefix:]
                   + zc * m.sym_tile)
        assert rebuilt == pre, f"{mode.name}: preamble not block-periodic"
        out.append(f"#define PRE_TONE_TILES_{mode.name} {T}")
        out.append(carr(f"PRE_TONEA_{mode.name}", tone_a, "int16_t"))
        out.append(carr(f"PRE_TONEB_{mode.name}", tone_b, "int16_t"))
        out.append(carr(f"PRE_ZC_{mode.name}", zc, "int16_t"))

    # --- RX demod constants -------------------------------------------------
    rx0 = FixedReceiver(LinkMode.NORMAL)
    m0 = rx0._m
    out.append(carr("PILOT_CARRIERS", m0._pilot_carriers.astype(int), "int16_t"))
    out.append(carr("PILOT_CONJ_RE", rx0.pilot_conj_rom[0], "int16_t"))
    out.append(carr("PILOT_CONJ_IM", rx0.pilot_conj_rom[1], "int16_t"))
    out.append(carr("INTERP_LO", [i[0] for i in rx0.interp], "int16_t"))
    out.append(carr("INTERP_HI", [i[1] for i in rx0.interp], "int16_t"))
    out.append(carr("INTERP_W", [i[2] for i in rx0.interp], "int32_t"))
    for mode in LinkMode:
        rx = FixedReceiver(mode)
        assert [tuple(t) for t in rx.interp] == [tuple(t) for t in rx0.interp]
        out.append(f"#define N_SEARCH_{mode.name} {len(rx.search_words)}")
        out.append(carr(f"SEARCH_WORDS_{mode.name}",
                        [int(w) for w in rx.search_words], "int32_t"))
    out.append(f"#define COARSE_GATE_Q4_C {FixedReceiver.COARSE_GATE_Q4}")

    # --- detection constants (tone + ZC stages), per mode -------------------
    for mode in LinkMode:
        rx = FixedReceiver(mode)
        nm = mode.name
        out += [f"#define DET_B_{nm} {rx.B}",
                f"#define DET_T_{nm} {rx.T}",
                f"#define DET_MAX_SHIFT_{nm} {rx.max_shift}",
                f"#define DET_NEWMAN_THR_Q10_{nm} {rx.newman_thr_q10}",
                f"#define DET_WORD_PER_BIN_{nm} {rx.word_per_fine_bin}",
                f"#define DET_N_MASK_BINS_{nm} {rx.n_mask_bins}",
                carr(f"DET_MASK0_{nm}", rx.masks[0], "uint8_t"),
                carr(f"DET_MASK1_{nm}", rx.masks[1], "uint8_t"),
                f"#define ZC_L_{nm} {rx.zc_L}",
                f"#define ZC_G_{nm} {rx.zc_G}",
                f"#define ZC_GROUPS_{nm} {rx.zc_groups}",
                f"#define ZC_REF_ENERGY_{nm} {rx.zc_ref_energy}",
                f"#define ZC_PRE_BLOCK_LEN_{nm} {rx.preamble_block_len}",
                f"#define ZC_THR_Q10_{nm} {rx.zc_thr_q10}",
                f"#define N_ZC_HYPS_{nm} {len(rx.zc_hyp_words)}",
                carr(f"ZC_HYP_WORDS_{nm}",
                     [int(w) for w in rx.zc_hyp_words], "int32_t"),
                carr(f"ZC_ROM_RE_{nm}", rx.zc_rom[0], "int16_t"),
                carr(f"ZC_ROM_IM_{nm}", rx.zc_rom[1], "int16_t")]
    # --- RX extras: calibration ROM, SNR-estimator constants ----------------
    out.append(carr("RECAL_ROM", FixedReceiver.RECAL_ROM, "int16_t"))
    out.append(carr("LOG2_FRAC_Q4", FixedReceiver.LOG2_FRAC_Q4, "int16_t"))
    out.append(f"#define SNR_CAL_DB {float(FixedReceiver.SNR_CAL_DB)!r}")
    out.append(f"#define TEN_LOG10_2 {float(10.0 * np.log10(2.0))!r}")
    for mode in LinkMode:
        rx = FixedReceiver(mode)
        out.append(f"#define TILE_DB_{mode.name} {float(rx._tile_db)!r}")
    out.append("#endif /* ROM_MODES_H */")
    (HERE / "src" / "rom_modes.h").write_text("\n".join(out))
    print("wrote src/rom_modes.h")


def gen_link_rom():
    """Rate ladder + controller scenario vectors -> src/rom_link.h."""
    from ofdm_phy.link import LADDER, LinkControl, LinkController
    out = ["/* generated by gen_vectors.py -- do not edit */",
           "#ifndef ROM_LINK_H", "#define ROM_LINK_H",
           "#include <stdint.h>", "",
           f"#define LADDER_N {len(LADDER)}"]
    out.append(carr("LADDER_MODE", [r.mode.value for r in LADDER], "int16_t"))
    out.append(carr("LADDER_MOD", [r.mod.value for r in LADDER], "int16_t"))
    out.append(carr("LADDER_SPD", [r.spd.value for r in LADDER], "int16_t"))
    out.append("static const double LADDER_SENS[LADDER_N] = { "
               + ", ".join(repr(float(r.sens_db)) for r in LADDER) + " };")
    out.append("static const double LADDER_RATE[LADDER_N] = { "
               + ", ".join(repr(float(r.user_rate)) for r in LADDER) + " };")

    # LC word golden vectors (incl. round-half-even edges)
    lcs = [LinkControl(seq=3, ack=1, req_rung=12, snr_db=-3.0,
                       freq_corr_hz=-48.0, flags=5),
           LinkControl(seq=0, ack=0, req_rung=0, snr_db=-24.0,
                       freq_corr_hz=0.0, flags=2),
           LinkControl(seq=2, ack=3, req_rung=15, snr_db=6.0,
                       freq_corr_hz=120.0, flags=7),
           LinkControl(seq=1, ack=2, req_rung=7, snr_db=-23.0,  # .5 rounding
                       freq_corr_hz=-4.0, flags=1),
           LinkControl(seq=1, ack=0, req_rung=3, snr_db=-21.0,  # .5 rounding
                       freq_corr_hz=12.0, flags=0)]
    out.append(carr("LC_PACKED", [lc.pack() for lc in lcs], "int32_t"))
    for i, lc in enumerate(lcs):
        u = LinkControl.unpack(lc.pack())
        out.append(f"#define LC{i}_SEQ {u.seq}")
        out.append(f"#define LC{i}_ACK {u.ack}")
        out.append(f"#define LC{i}_RUNG {u.req_rung}")
        out.append(f"#define LC{i}_SNR {float(u.snr_db)!r}")
        out.append(f"#define LC{i}_FREQ {float(u.freq_corr_hz)!r}")
        out.append(f"#define LC{i}_FLAGS {u.flags}")

    # controller parity trace: scripted ops, python outputs as golden.
    # op codes: 0 rx_frame(snr, req, report, t); 1 -> q=rx_request(t);
    # 2 -> q=tx_rung(t); 3 on_timeout; 4 on_ack; 5 note_outcome(rung, ok);
    # 6 -> q=filtered_snr(t)*1000 rounded; 7 -> q=tx_rung_for_class(t, ctl)
    ctl = LinkController()
    ops = []

    def rx(snr, req, rep, t):
        ctl.on_rx_frame(snr, LinkControl(req_rung=req, snr_db=rep), t)
        ops.append((0, snr, req, rep, t, 0))

    def q_req(t):
        ops.append((1, 0, 0, 0, t, ctl.rx_request(t)))

    def q_tx(t):
        ops.append((2, 0, 0, 0, t, ctl.tx_rung(t)))

    def q_snr(t):
        ops.append((6, 0, 0, 0, t, int(round(ctl.filtered_snr(t) * 1000))))

    def q_txc(t):
        ops.append((7, 0, 0, 0, t, ctl.tx_rung_for_class(t, "control")))

    # bootstrap + fast start
    q_req(0.0); q_tx(0.0)
    rx(-16.0, 0, -24.0, 1.0); q_req(1.5); q_snr(1.5)
    rx(-8.0, 3, -6.0, 10.0); rx(-7.5, 4, -6.0, 20.0)
    rx(-7.8, 5, -5.8, 30.0); q_req(31.0); q_tx(31.0); q_txc(31.0); q_snr(31.0)
    # upshift with margin
    rx(-2.0, 7, -1.0, 40.0); rx(-1.5, 8, -0.5, 50.0); rx(-1.8, 8, -0.4, 55.0)
    q_req(56.0); q_tx(56.0)
    # fade: downshift + report cap
    rx(-12.0, 2, -13.0, 60.0); rx(-12.5, 1, -13.5, 62.0)
    rx(-12.2, 1, -13.2, 64.0); q_req(65.0); q_tx(65.0)
    # loss fallback
    ops.append((3, 0, 0, 0, 66.0, 0)); ctl.on_timeout()
    ops.append((3, 0, 0, 0, 70.0, 0)); ctl.on_timeout()
    q_tx(71.0)
    ops.append((3, 0, 0, 0, 74.0, 0)); ctl.on_timeout()
    ops.append((3, 0, 0, 0, 78.0, 0)); ctl.on_timeout()
    q_tx(79.0)
    ops.append((4, 0, 0, 0, 80.0, 0)); ctl.on_ack()
    q_tx(81.0)
    # learned offsets
    for k in range(4):
        ops.append((5, 6, 0, 0, 82.0 + k, 0)); ctl.note_outcome(6, False)
    q_tx(86.0)
    ops.append((5, 6, 1, 0, 87.0, 0)); ctl.note_outcome(6, True)
    q_tx(88.0)
    # inbound silence decay + history purge
    q_req(120.0); q_req(200.0); q_snr(200.0)
    # stale peer request decay
    q_tx(300.0)

    out.append(f"#define CTL_OPS_N {len(ops)}")
    out.append(carr("CTL_OP", [o[0] for o in ops], "int16_t"))
    out.append("static const double CTL_A[CTL_OPS_N] = { "
               + ", ".join(repr(float(o[1])) for o in ops) + " };")
    out.append(carr("CTL_B", [o[2] for o in ops], "int16_t"))
    out.append("static const double CTL_C[CTL_OPS_N] = { "
               + ", ".join(repr(float(o[3])) for o in ops) + " };")
    out.append("static const double CTL_T[CTL_OPS_N] = { "
               + ", ".join(repr(float(o[4])) for o in ops) + " };")
    out.append(carr("CTL_WANT", [o[5] for o in ops], "int32_t"))
    out.append("#endif /* ROM_LINK_H */")
    (HERE / "src" / "rom_link.h").write_text("\n".join(out))
    print("wrote src/rom_link.h")


def gen_ldpc_rom():
    """IRA LDPC graph -> src/rom_ldpc.h (dumped, never rebuilt in C)."""
    from ofdm_phy import ldpc as L
    out = ["/* generated by gen_vectors.py -- do not edit */",
           "#ifndef ROM_LDPC_H", "#define ROM_LDPC_H",
           "#include <stdint.h>", "",
           f"#define LDPC_N {L.N}", f"#define LDPC_K {L.K_NOMINAL}",
           f"#define LDPC_M {L.M}", f"#define LDPC_DC_MAX {L.DC_MAX}",
           f"#define LDPC_MAX_ITER {L.MAX_ITER}", ""]
    out.append(carr("LDPC_EV", L._EV.ravel(), "int16_t"))
    max_info = max(len(c) for c in L._CHK_INFO)
    ci = np.full((L.M, max_info), -1, dtype=np.int64)
    for c, vs in enumerate(L._CHK_INFO):
        ci[c, :len(vs)] = vs
    out.append(f"#define LDPC_CI_MAX {max_info}")
    out.append(carr("LDPC_CHK_INFO", ci.ravel(), "int16_t"))
    out.append("#endif /* ROM_LDPC_H */")
    (HERE / "src" / "rom_ldpc.h").write_text("\n".join(out))
    print("wrote src/rom_ldpc.h")

HERE = Path(__file__).resolve().parent


def carr(name, arr, ctype="int64_t", static=True):
    vals = ",\n    ".join(", ".join(str(int(v)) for v in arr[i:i + 8])
                          for i in range(0, len(arr), 8))
    qual = "static const" if static else "const"
    return f"{qual} {ctype} {name}[{len(arr)}] = {{\n    {vals}\n}};\n"


def gen_roms():
    out = ["/* generated by gen_vectors.py -- do not edit */",
           "#ifndef ROM_TABLES_H", "#define ROM_TABLES_H",
           "#include <stdint.h>", ""]
    # single trig ROM: NCO_SIN and every FFT twiddle table are exact
    # views of NCO_COS (sin[i] = cos[(i+3072)&4095]; twiddle_n[k] =
    # cos/-sin at stride 4096/n) -- verified here, consumed via index
    # arithmetic in dsp.c/fft.c. Was 18.2 KB of tables, now 8 KB.
    cos_rom, sin_rom = NCO._rom()
    N = len(cos_rom)
    assert all(int(sin_rom[i]) == int(cos_rom[(i + 3 * N // 4) % N])
               for i in range(N))
    for n in (128, 256, 512):
        wr, wi = _twiddles(n)
        st = N // n
        assert all(int(wr[k]) == int(cos_rom[(k * st) % N])
                   and int(wi[k]) == -int(sin_rom[(k * st) % N])
                   for k in range(n // 2))
    out.append(f"#define NCO_LUT_N {N}")
    # NCO_COS is shared by dsp.c AND fft.c -- a static-in-header table
    # would be duplicated into both objects (8 KB twice), so the owner
    # TU defines ROM_TABLES_DEFINE and everyone else gets an extern.
    out.append("#ifdef ROM_TABLES_DEFINE")
    out.append(carr("NCO_COS", cos_rom, "int16_t", static=False))
    out.append("#else")
    out.append(f"extern const int16_t NCO_COS[{N}];")
    out.append("#endif")
    h = HilbertFIR()
    out.append(carr("HILBERT_TAPS", h.taps_q15, "int16_t"))
    out.append(carr("CORDIC_ATAN", _CORDIC_ATAN, "int64_t"))
    out.append(f"#define CORDIC_GAIN_Q15 {_CORDIC_GAIN_Q15}\n")
    out.append("#endif /* ROM_TABLES_H */")
    (HERE / "src" / "rom_tables.h").write_text("\n".join(out))
    print("wrote src/rom_tables.h")


def gen_vectors():
    rng = np.random.default_rng(20260816)
    out = ["/* generated by gen_vectors.py -- do not edit */",
           "#ifndef TEST_VECTORS_H", "#define TEST_VECTORS_H",
           "#include <stdint.h>", ""]

    # --- FFT / IFFT / BFP ---------------------------------------------------
    for n in (128, 256, 512):
        xr = rng.integers(-32768, 32768, n)
        xi = rng.integers(-32768, 32768, n)
        fr, fi = fft_fixed(xr, xi)
        out += [carr(f"FFT{n}_IN_RE", xr), carr(f"FFT{n}_IN_IM", xi),
                carr(f"FFT{n}_OUT_RE", fr), carr(f"FFT{n}_OUT_IM", fi)]
    xr = rng.integers(-32768, 32768, 128)
    xi = rng.integers(-32768, 32768, 128)
    ir, ii = ifft_fixed(xr, xi)
    out += [carr("IFFT128_IN_RE", xr), carr("IFFT128_IN_IM", xi),
            carr("IFFT128_OUT_RE", ir), carr("IFFT128_OUT_IM", ii)]
    # BFP: a weak block (positive exp) and a hot block (negative exp)
    for tag, scale in (("WEAK", 37), ("HOT", 250000)):
        xr = rng.integers(-scale, scale, 512)
        xi = rng.integers(-scale, scale, 512)
        br, bi, be = fft_bfp(xr, xi, 13)
        out += [carr(f"BFP_{tag}_IN_RE", xr), carr(f"BFP_{tag}_IN_IM", xi),
                carr(f"BFP_{tag}_OUT_RE", br), carr(f"BFP_{tag}_OUT_IM", bi),
                f"#define BFP_{tag}_EXP {be}\n"]

    # --- Hilbert ------------------------------------------------------------
    t = np.arange(2048)
    x = (12000 * np.cos(2 * np.pi * 700 * t / 12000)
         + rng.integers(-8000, 8000, len(t))).astype(np.int64)
    x = np.clip(x, -32768, 32767)
    h = HilbertFIR()
    hi, hq = h.analytic(x)
    out += [carr("HILBERT_IN", x, "int16_t"),
            carr("HILBERT_OUT_I", hi), carr("HILBERT_OUT_Q", hq)]

    # --- NCO derotate -------------------------------------------------------
    word = 3126742  # ~8.74 Hz at 12 kHz
    start = 0x1234ABCD
    ni = rng.integers(-30000, 30000, 1024)
    nq = rng.integers(-30000, 30000, 1024)
    oi, oq = NCO.derotate(ni, nq, word, start_phase=start)
    out += [carr("NCO_IN_I", ni), carr("NCO_IN_Q", nq),
            f"#define NCO_WORD {word}", f"#define NCO_START {start}\n",
            carr("NCO_OUT_I", oi), carr("NCO_OUT_Q", oq)]
    # negative word (conjugate rotation), nonzero start
    word2 = -19876543
    oi2, oq2 = NCO.derotate(ni, nq, word2, start_phase=7)
    out += [f"#define NCO_WORD2 ({word2})",
            carr("NCO_OUT2_I", oi2), carr("NCO_OUT2_Q", oq2)]

    # --- CORDIC -------------------------------------------------------------
    ys = list(rng.integers(-(1 << 30), 1 << 30, 60)) + \
        [0, 1, -1, (1 << 30), -(1 << 30), 0, 12345, -12345]
    xs = list(rng.integers(-(1 << 30), 1 << 30, 60)) + \
        [1, 0, 0, -(1 << 30), (1 << 30), -7, -12345, 12345]
    ang = []
    mag = []
    for y, x_ in zip(ys, xs):
        a, m = cordic_atan2(int(y), int(x_))
        ang.append(a)
        mag.append(m)
    out += [carr("CORDIC_Y", ys), carr("CORDIC_X", xs),
            carr("CORDIC_ANG", ang), carr("CORDIC_MAG", mag)]

    # --- bit pipeline -------------------------------------------------------
    bits = rng.integers(0, 2, 120).astype(np.uint8)
    out += [carr("CRC_BITS", bits, "uint8_t"),
            f"#define CRC8_WANT {crc8_lte(bits)}",
            f"#define CRC16_WANT {crc16_ccitt(bits)}\n"]

    sb = rng.integers(0, 2, 200).astype(np.uint8)
    out += [carr("SCR_IN", sb, "uint8_t"),
            carr("SCR_OUT", scramble(sb), "uint8_t")]
    llrs = rng.integers(-31, 32, 200)
    out += [carr("DESCR_IN", llrs),
            carr("DESCR_OUT",
                 descramble(llrs.astype(np.float64)).astype(np.int64))]

    il_in = rng.integers(0, 2, 93).astype(np.uint8)
    out += [carr("IL_IN", il_in, "uint8_t"),
            carr("IL_OUT", interleave(il_in, 16), "uint8_t")]
    dl_in = rng.integers(-1000, 1000, 93)
    out += [carr("DL_IN", dl_in),
            carr("DL_OUT", deinterleave(dl_in, 16))]

    payload = rng.integers(0, 2, 100).astype(np.uint8)
    out.append(carr("CONV_PAYLOAD", payload, "uint8_t"))
    for name, codec in RATES:
        coded = codec.encode(payload)
        out.append(carr(f"CONV_{name}_CODED", coded, "uint8_t"))
        clean = (2 * coded.astype(np.int64) - 1) * 25
        noisy = np.clip(clean + rng.integers(-25, 26, len(clean)), -31, 31)
        dec = viterbi_decode_int(codec, noisy, len(payload))
        out += [carr(f"CONV_{name}_NOISY", noisy),
                carr(f"CONV_{name}_DEC", dec, "uint8_t")]

    # --- packets ------------------------------------------------------------
    hdr = Header(ver=1, typ=PacketType.DATA, mod=ModType.QPSK,
                 spd=CCSpeed.R23, len=180)
    out.append(carr("HDR_BITS_WANT", hdr.encode(), "uint8_t"))
    dpkt = Data(reserved=0x5A5A5, payload=bytes(range(17)))
    out.append(carr("DATA_BITS_WANT", dpkt.encode(), "uint8_t"))
    out.append(carr("DATA_PAYLOAD", np.frombuffer(dpkt.payload, np.uint8),
                    "uint8_t"))

    # --- full TX frames (FNV-1a 64 hash + head samples for debugging) -------
    tx_cases = [
        ("NORM_BPSK", LinkMode.NORMAL, ModType.BPSK, CCSpeed.R13,
         Data(reserved=123, payload=bytes(range(17)))),
        ("NORM_QPSK", LinkMode.NORMAL, ModType.QPSK, CCSpeed.R23,
         Data(reserved=0xFFFFF, payload=bytes(range(40, 61)))),
        ("NORM_QAM16", LinkMode.NORMAL, ModType.QAM16, CCSpeed.R12,
         Data(reserved=7, payload=bytes(range(100, 121)))),
        ("ROBUST_BPSK", LinkMode.ROBUST, ModType.BPSK, CCSpeed.R13,
         Data(reserved=42, payload=bytes(range(9)))),
        ("EXTREME_BPSK", LinkMode.EXTREME, ModType.BPSK, CCSpeed.R13,
         Data(reserved=99, payload=bytes(4))),
    ]
    txs = {}
    for tag, mode, mod, spd, pkt in tx_cases:
        if mode not in txs:
            txs[mode] = FixedTransmitter(mode)
        sig = txs[mode].build_frame(pkt, mod=mod, spd=spd)
        out += [carr(f"TX_{tag}_PKT", pkt.encode(), "uint8_t"),
                f"#define TX_{tag}_MODE {list(LinkMode).index(mode)}",
                f"#define TX_{tag}_MOD {mod.value}",
                f"#define TX_{tag}_SPD {spd.value}",
                f"#define TX_{tag}_LEN {len(sig)}",
                f"#define TX_{tag}_HASH UINT64_C({fnv64_i16(sig)})",
                carr(f"TX_{tag}_HEAD", sig[:64], "int16_t")]

    # --- streamed burst (tx_build_burst / rxd_receive_burst) ---------------
    # one preamble + one header for N equal blocks, ZC resync every R.
    # The C builder must match the fixed model sample for sample: the clip
    # threshold is a whole-waveform RMS, so a burst is NOT the concatenation
    # of separately built frames.
    burst_blocks = [Data(reserved=5 + i, payload=bytes(range(i, i + 12)))
                    for i in range(6)]
    burst_mode, burst_mod, burst_spd, burst_resync = (
        LinkMode.NORMAL, ModType.QPSK, CCSpeed.R12, 2)
    if burst_mode not in txs:
        txs[burst_mode] = FixedTransmitter(burst_mode)
    bsig = txs[burst_mode].build_stream(burst_blocks, mod=burst_mod,
                                        spd=burst_spd,
                                        resync_every=burst_resync)
    bbits = np.concatenate([b.encode() for b in burst_blocks])
    out += [carr("TX_BURST_BITS", bbits, "uint8_t"),
            f"#define TX_BURST_MODE {list(LinkMode).index(burst_mode)}",
            f"#define TX_BURST_MOD {burst_mod.value}",
            f"#define TX_BURST_SPD {burst_spd.value}",
            f"#define TX_BURST_N {len(burst_blocks)}",
            f"#define TX_BURST_RESYNC {burst_resync}",
            f"#define TX_BURST_PKT_BITS {len(burst_blocks[0].encode())}",
            f"#define TX_BURST_LEN {len(bsig)}",
            f"#define TX_BURST_HASH UINT64_C({fnv64_i16(bsig)})",
            carr("TX_BURST_HEAD", bsig[:64], "int16_t")]

    # --- genie-synced RX demod cases ---------------------------------------
    # clean frames are rebuilt in C by the (bit-exact) C TX, so only the
    # detection genie (start, cfo_word) and expected bits are dumped
    pad = np.zeros(700, dtype=np.int16)
    rxs = {}
    for tag, mode, mod, spd, pkt in tx_cases:
        if mode not in rxs:
            rxs[mode] = FixedReceiver(mode)
        rx = rxs[mode]
        sig = txs[mode].build_frame(pkt, mod=mod, spd=spd)
        samples = np.concatenate([pad, sig])
        i_arr, q_arr = rx.hilbert.analytic(np.asarray(samples, dtype=np.int64))
        det = rx._detect(i_arr, q_arr)
        assert det is not None, f"detection failed for {tag}"
        start, cfo_word = det
        dec, hdr, *_ = rx.receive(samples)
        assert np.array_equal(dec.encode(), pkt.encode())
        out += [f"#define RX_{tag}_START {start}",
                f"#define RX_{tag}_CFO_WORD INT64_C({int(cfo_word)})",
                f"#define RX_{tag}_PKT_BITS {len(pkt.encode())}\n"]

    # noisy case: embedded samples (deterministic channel), NORMAL BPSK 1/3
    from ofdm_phy import simulate_channel
    nrng = np.random.default_rng(424242)
    npkt = Data(reserved=555, payload=bytes(range(200, 227)))
    nsig = txs[LinkMode.NORMAL].build_frame(npkt)
    nrx = simulate_channel(nsig.astype(np.float64), 700, 41.0, 12000,
                           snr_db=-5.0, rng=nrng)
    n16 = np.clip(nrx / np.max(np.abs(nrx)) * 0.9 * 32767,
                  -32768, 32767).astype(np.int16)
    rxn = FixedReceiver(LinkMode.NORMAL)
    i_arr, q_arr = rxn.hilbert.analytic(np.asarray(n16, dtype=np.int64))
    det = rxn._detect(i_arr, q_arr)
    assert det is not None
    dec, hdr, *_ = rxn.receive(n16)
    assert np.array_equal(dec.encode(), npkt.encode())
    out += [carr("RX_NOISY_SAMPLES", n16, "int16_t"),
            carr("RX_NOISY_PKT", npkt.encode(), "uint8_t"),
            f"#define RX_NOISY_START {det[0]}",
            f"#define RX_NOISY_CFO_WORD INT64_C({int(det[1])})\n"]

    # --- LDPC unit vectors --------------------------------------------------
    from ofdm_phy.ldpc import LDPCCodec, ldpc_decode_int as pldpc_dec
    kk = 236
    lb = rng.integers(0, 2, kk).astype(np.uint8)
    lcoded = LDPCCodec.encode(lb)
    clean = (2 * lcoded.astype(np.int64) - 1) * 20
    lnoisy = np.clip(clean + rng.integers(-28, 29, len(clean)), -31, 31)
    ldec = pldpc_dec(lnoisy, kk)
    out += [carr("LDPC_INFO", lb, "uint8_t"),
            carr("LDPC_CODED", lcoded, "uint8_t"),
            carr("LDPC_NOISY", lnoisy),
            carr("LDPC_DEC", ldec, "uint8_t")]

    # --- LDPC (ver=2) frame: TX hash + RX genie -----------------------------
    lpkt = Data(reserved=321, payload=bytes(range(60, 87)))
    lsig = txs[LinkMode.NORMAL].build_frame(lpkt, mod=ModType.BPSK,
                                            spd=CCSpeed.R13, fec="ldpc")
    out += [carr("TX_LDPC_PKT", lpkt.encode(), "uint8_t"),
            f"#define TX_LDPC_LEN {len(lsig)}",
            f"#define TX_LDPC_HASH UINT64_C({fnv64_i16(lsig)})",
            carr("TX_LDPC_HEAD", lsig[:64], "int16_t")]
    lsamp = np.concatenate([pad, lsig])
    rxl = rxs[LinkMode.NORMAL]
    det = rxl._detect(*rxl.hilbert.analytic(np.asarray(lsamp, np.int64)))
    assert det is not None
    decl, hdrl, *_ = rxl.receive(lsamp)
    assert hdrl.ver == 2 and np.array_equal(decl.encode(), lpkt.encode())
    out += [f"#define RX_LDPC_START {det[0]}",
            f"#define RX_LDPC_CFO_WORD INT64_C({int(det[1])})\n"]

    # --- HARQ: complementary erasures on a calibrated RX --------------------
    from ofdm_phy.transceiver import DemodError
    hpkt = Data(reserved=99, payload=bytes(range(27)))
    hsig = txs[LinkMode.NORMAL].build_frame(hpkt)
    hs = np.concatenate([pad, hsig])
    hdr_end = 700 + 4384 + 6 * rxl.symbol_len + 31
    dlen = len(hs) - hdr_end
    ea0, ea1 = hdr_end + int(0.02 * dlen), hdr_end + int(0.77 * dlen)
    eb0, eb1 = hdr_end + int(0.23 * dlen), hdr_end + int(0.98 * dlen)
    ha, hb = hs.copy(), hs.copy()
    ha[ea0:ea1] = 0
    hb[eb0:eb1] = 0
    rxc = FixedReceiver(LinkMode.NORMAL, calibrate=True)
    deta = rxc._detect(*rxc.hilbert.analytic(np.asarray(ha, np.int64)))
    detb = rxc._detect(*rxc.hilbert.analytic(np.asarray(hb, np.int64)))
    assert deta is not None and detb is not None
    stored = None
    try:
        rxc.receive(ha)
        raise AssertionError("erased copy A should fail")
    except DemodError as exc:
        stored = exc.data_llrs
    decb, *_ = rxc.receive(hb, prev_data_llrs=stored)
    assert np.array_equal(decb.encode(), hpkt.encode())
    out += [carr("HARQ_PKT", hpkt.encode(), "uint8_t"),
            f"#define HARQ_EA0 {ea0}", f"#define HARQ_EA1 {ea1}",
            f"#define HARQ_EB0 {eb0}", f"#define HARQ_EB1 {eb1}",
            f"#define HARQ_A_START {deta[0]}",
            f"#define HARQ_A_CFO_WORD INT64_C({int(deta[1])})",
            f"#define HARQ_B_START {detb[0]}",
            f"#define HARQ_B_CFO_WORD INT64_C({int(detb[1])})",
            f"#define HARQ_LLR_N {len(stored)}",
            f"#define HARQ_LLR_HASH UINT64_C({fnv64_i64(stored)})\n"]

    # --- calibrate + SNR estimate on the noisy frame ------------------------
    rxc2 = FixedReceiver(LinkMode.NORMAL, calibrate=True)
    capture = {}
    orig_cal = rxc2._calibrated_llrs

    def _wrap(d64, scale_d, alpha_q12, hsf):
        res = orig_cal(d64, scale_d, alpha_q12, hsf)
        capture["llr"] = res
        return res

    rxc2._calibrated_llrs = _wrap
    decn2, *_ = rxc2.receive(n16)
    assert np.array_equal(decn2.encode(), npkt.encode())
    assert "llr" in capture
    out += [f"#define CAL_LLR_N {len(capture['llr'])}",
            f"#define CAL_LLR_HASH UINT64_C({fnv64_i64(capture['llr'])})",
            f"#define CAL_SNR_DB {float(rxc2.last_stats.snr_db)!r}\n"]

    out.append("#endif /* TEST_VECTORS_H */")
    (HERE / "tests" / "test_vectors.h").write_text("\n".join(out))
    print("wrote tests/test_vectors.h")


if __name__ == "__main__":
    (HERE / "src").mkdir(exist_ok=True)
    (HERE / "tests").mkdir(exist_ok=True)
    gen_roms()
    gen_mode_roms()
    gen_ldpc_rom()
    gen_link_rom()
    gen_vectors()
